export function generateFooterHTML(
  jurisdiction: 'IN' | 'GLOBAL', 
  documentType: string, 
  isProUser: boolean
): string {
  const currentDate = new Date().toLocaleDateString('en-IN', { 
    year: 'numeric', month: 'long', day: 'numeric' 
  });

  const jurisdictionText = jurisdiction === 'IN' 
    ? 'the Information Technology Act 2000, the Digital Personal Data Protection (DPDP) Act 2023, and the Consumer Protection Act 2019' 
    : 'general international standards, including GDPR and CCPA principles';
  
  const badge = jurisdiction === 'IN' 
    ? '<span style="background:#ecfdf5;color:#065f46;padding:4px 10px;border-radius:999px;font-size:11px;font-weight:600;border:1px solid #a7f3d0;">🇮🇳 DPDP Act Ready</span>'
    : '<span style="background:#eff6ff;color:#1e40af;padding:4px 10px;border-radius:999px;font-size:11px;font-weight:600;border:1px solid #bfdbfe;">🌍 GDPR Aligned</span>';

  // IMPORTANT: Change 'https://your-footer-domain.com' to your actual website URL!
  const attribution = !isProUser ? `
    <div style="margin-top:24px;text-align:center;font-size:13px;color:#6b7280;border-top:1px dashed #d1d5db;padding-top:16px;">
      Generated by <a href="https://your-footer-domain.com" target="_blank" style="font-weight:bold;color:#4f46e5;text-decoration:underline;">FOOTER</a>. 
      <a href="https://your-footer-domain.com/pricing" target="_blank" style="color:#4f46e5;font-weight:600;text-decoration:none;">Upgrade to Pro</a> to remove this attribution, unlock PDF/DOCX exports, and enable auto-updating policies.
    </div>
  ` : '';

  return `
    <div style="margin-top:48px;padding-top:32px;border-top:2px solid #e5e7eb;font-size:14px;color:#4b5563;font-family:system-ui, -apple-system, sans-serif;">
      <div style="background:#f9fafb;padding:20px;border-radius:8px;border:1px solid #e5e7eb;margin-bottom:20px;">
        <p style="font-weight:700;color:#1f2937;margin:0 0 10px 0;font-size:15px;">⚖️ Legal Disclaimer</p>
        <p style="line-height:1.6;margin:0;font-size:13px;">
          This ${documentType} is a template generated for informational purposes based on the details provided. 
          It is designed to align with ${jurisdictionText}. 
          This document does not constitute formal legal advice. We strongly recommend having a qualified legal professional in your jurisdiction review this document before publication to ensure full compliance with your specific business operations.
        </p>
      </div>

      <div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:16px;font-size:12px;color:#6b7280;">
        <div>
          <p style="margin:0 0 4px 0;">Generated on: <span style="font-weight:600;color:#374151;">${currentDate}</span></p>
          <p style="margin:0;">Jurisdiction Framework: <span style="font-weight:600;color:#374151;">${jurisdiction === 'IN' ? 'India' : 'Global'}</span></p>
        </div>
        <div style="display:flex;gap:8px;align-items:center;">
          ${badge}
          <span style="background:#f3f4f6;color:#374151;padding:4px 10px;border-radius:999px;font-size:11px;font-weight:600;border:1px solid #d1d5db;">AI-Assisted Draft</span>
        </div>
      </div>

      ${attribution}
    </div>
  `;
}