// src/lib/legal-engine/website-analyzer.ts
import type { FeatureMap, FeatureKey } from './types';

interface DetectionRule {
    feature: FeatureKey;
    keywords: string[];
}

const DETECTION_RULES: DetectionRule[] = [
    { feature: 'hasLogin', keywords: ['sign in', 'log in', 'login', 'sign up', 'create account', 'register'] },
    { feature: 'hasPayments', keywords: ['checkout', 'add to cart', 'buy now', 'pricing', 'subscribe now', 'payment'] },
    { feature: 'hasSubscriptions', keywords: ['subscription', 'monthly plan', 'annual plan', '/month', '/mo', 'billing cycle'] },
    { feature: 'shipsPhysicalGoods', keywords: ['shipping', 'delivery', 'track your order', 'free shipping'] },
    { feature: 'hasBookingSystem', keywords: ['book now', 'reserve', 'booking', 'check-in', 'check-out', 'appointment', 'schedule a'] },
    { feature: 'hasUserGeneratedContent', keywords: ['write a review', 'post a comment', 'upload your', 'share your', 'leave a review'] },
    { feature: 'hasAiFeatures', keywords: ['ai-powered', 'artificial intelligence', 'chatbot', 'generated by ai', 'machine learning'] },
    { feature: 'hasCookiesAnalytics', keywords: ['cookie', 'google analytics', 'gtag', 'facebook pixel', 'we use cookies'] },
    { feature: 'hasNewsletter', keywords: ['newsletter', 'subscribe to our', 'get updates', 'mailing list'] },
    { feature: 'hasFileUploads', keywords: ['upload a file', 'upload your', 'drag and drop', 'choose file'] },
    { feature: 'hasReviews', keywords: ['reviews', 'testimonial', 'star rating'] },
];

export interface DetectedFeature {
    feature: FeatureKey;
    matchedKeywords: string[];
}

export interface WebsiteAnalysisResult {
    features: Partial<FeatureMap>;
    detections: DetectedFeature[];
}

export function analyzeWebsiteText(pageText: string): WebsiteAnalysisResult {
    const lowerText = pageText.toLowerCase();
    const features: Partial<FeatureMap> = {};
    const detections: DetectedFeature[] = [];

    for (const rule of DETECTION_RULES) {
        const matched = rule.keywords.filter((kw) => lowerText.includes(kw));
        if (matched.length > 0) {
            features[rule.feature] = true;
            detections.push({ feature: rule.feature, matchedKeywords: matched });
        }
    }

    return { features, detections };
}

export const FEATURE_LABELS: Record<FeatureKey, string> = {
    hasLogin: 'User Login / Accounts',
    hasPayments: 'Payments / Checkout',
    hasSubscriptions: 'Subscriptions / Recurring Billing',
    shipsPhysicalGoods: 'Physical Product Shipping',
    hasBookingSystem: 'Booking / Reservation System',
    hasUserGeneratedContent: 'User-Generated Content',
    hasAiFeatures: 'AI-Powered Features',
    hasCookiesAnalytics: 'Cookies / Analytics Tracking',
    hasNewsletter: 'Newsletter / Email Signup',
    hasInternationalUsers: 'International Users',
    collectsChildrenData: "Children's Data",
    hasFileUploads: 'File Uploads',
    hasReviews: 'Reviews / Ratings',
};

export function featuresToFormData(features: Partial<FeatureMap>): Record<string, boolean> {
    const map: Record<string, boolean> = {};
    if (features.hasLogin) map.hasAccounts = true;
    if (features.hasPayments) map.sellsProducts = true;
    if (features.hasSubscriptions) map.hasSubscriptions = true;
    if (features.hasUserGeneratedContent) map.userGeneratedContent = true;
    if (features.hasAiFeatures) map.usesAi = true;
    if (features.hasCookiesAnalytics) map.usesCookies = true;
    if (features.hasNewsletter) map.hasNewsletter = true;
    if (features.hasBookingSystem) map.hasBookingSystem = true;
    return map;
}