import React from "react";
import {
    Shield, FileText, RefreshCcw, Cookie, AlertTriangle, Truck, Ban,
    FileX, ArrowLeft, Gauge, ScrollText, Megaphone, ShieldCheck, Database,
    AlertOctagon, ShieldAlert, Smartphone, ShoppingBag, Hotel, UtensilsCrossed,
    Stethoscope, GraduationCap, Landmark, Building, Film, Store, Briefcase,
    Building2, Code, Users, Heart, TrendingUp, Lightbulb, Zap
} from "lucide-react";
import type { DocumentType } from "@/lib/legalgen/types";

export const DOC_CONFIGS = [
    { type: "privacy-policy" as DocumentType, title: "Privacy Policy", description: "IT Act 2000, DPDP Act 2023, IT Rules 2021 compliant. Data collection, user rights, data principal requests, and grievance redressal.", icon: <Shield className="w-6 h-6" />, color: "text-emerald-700", bgColor: "bg-emerald-50", borderColor: "border-emerald-200", badge: "Most Popular", category: "Core", laws: ["IT Act 2000", "DPDP Act 2023", "IT Rules 2021"] },
    { type: "terms-of-service" as DocumentType, title: "Terms of Service", description: "User accounts, IP rights, liability limits, termination, governing law, and arbitration under Indian law.", icon: <FileText className="w-6 h-6" />, color: "text-slate-700", bgColor: "bg-slate-50", borderColor: "border-slate-200", badge: "Essential", category: "Core", laws: ["IT Act 2000", "Arbitration Act 1996", "Indian Contract Act"] },
    { type: "refund-policy" as DocumentType, title: "Refund Policy", description: "Consumer Protection Act 2019 compliant. Refund timelines, refund methods, partial/full refunds, and chargeback handling.", icon: <RefreshCcw className="w-6 h-6" />, color: "text-orange-700", bgColor: "bg-orange-50", borderColor: "border-orange-200", badge: "E-commerce", category: "Core", laws: ["Consumer Protection Act 2019", "E-Commerce Rules 2020"] },
    { type: "cookie-policy" as DocumentType, title: "Cookie Policy", description: "Cookie types, consent management, third-party disclosures, and user control over tracking preferences.", icon: <Cookie className="w-6 h-6" />, color: "text-amber-700", bgColor: "bg-amber-50", borderColor: "border-amber-200", badge: "GDPR Ready", category: "Core", laws: ["IT Act 2000", "IT Rules 2021", "DPDP Act 2023"] },
    { type: "disclaimer" as DocumentType, title: "Disclaimer", description: "Medical, legal, financial disclaimers, affiliate disclosures, and limitation of liability clauses.", icon: <AlertTriangle className="w-6 h-6" />, color: "text-red-700", bgColor: "bg-red-50", borderColor: "border-red-200", badge: "Protection", category: "Core", laws: ["IT Act 2000", "Consumer Protection Act 2019"] },
    { type: "shipping-policy" as DocumentType, title: "Shipping Policy", description: "Delivery timelines, shipping costs, COD availability, lost shipment policies, and tracking info.", icon: <Truck className="w-6 h-6" />, color: "text-blue-700", bgColor: "bg-blue-50", borderColor: "border-blue-200", badge: "Sellers", category: "Core", laws: ["Consumer Protection Act 2019", "E-Commerce Rules 2020"] },
    { type: "acceptable-use-policy" as DocumentType, title: "Acceptable Use Policy", description: "Prohibited activities, content rules, system usage limits, user responsibilities, and enforcement actions.", icon: <Ban className="w-6 h-6" />, color: "text-violet-700", bgColor: "bg-violet-50", borderColor: "border-violet-200", badge: "Platforms", category: "Operations", laws: ["IT Act 2000 (Sec 43,66,67)", "BNS 2023", "Consumer Protection Act"] },
    { type: "cancellation-policy" as DocumentType, title: "Cancellation Policy", description: "Cancellation windows, non-cancellable items, cancellation charges, refund processing, and subscription termination.", icon: <FileX className="w-6 h-6" />, color: "text-rose-700", bgColor: "bg-rose-50", borderColor: "border-rose-200", badge: "E-commerce", category: "Operations", laws: ["Consumer Protection Act 2019", "E-Commerce Rules 2020", "RBI Payment Aggregators"] },
    { type: "return-policy" as DocumentType, title: "Return Policy", description: "Return eligibility, return process, product inspection, exchange rules, and damaged/defective item returns.", icon: <ArrowLeft className="w-6 h-6" />, color: "text-purple-700", bgColor: "bg-purple-50", borderColor: "border-purple-200", badge: "E-commerce", category: "Operations", laws: ["Consumer Protection Act 2019", "Sale of Goods Act 1930", "E-Commerce Rules 2020"] },
    { type: "service-level-agreement" as DocumentType, title: "Service Level Agreement", description: "Uptime guarantees, response/resolution times, maintenance windows, service credits, and performance metrics.", icon: <Gauge className="w-6 h-6" />, color: "text-cyan-700", bgColor: "bg-cyan-50", borderColor: "border-cyan-200", badge: "SaaS", category: "Operations", laws: ["Indian Contract Act 1872", "Arbitration Act 1996", "CERT-In 2022"] },
    { type: "end-user-license-agreement" as DocumentType, title: "End User License Agreement", description: "License grant, IP ownership, restrictions, warranty disclaimer, liability limits, and governing law.", icon: <ScrollText className="w-6 h-6" />, color: "text-indigo-700", bgColor: "bg-indigo-50", borderColor: "border-indigo-200", badge: "Software", category: "Agreements", laws: ["Copyright Act 1957", "IT Act 2000", "Indian Contract Act"] },
    { type: "community-guidelines" as DocumentType, title: "Community Guidelines", description: "Community values, content standards, user behavior rules, moderation approach, and children's safety.", icon: <Megaphone className="w-6 h-6" />, color: "text-teal-700", bgColor: "bg-teal-50", borderColor: "border-teal-200", badge: "Community", category: "Agreements", laws: ["IT Act 2000 (Sec 67,79)", "BNS 2023", "IT Rules 2021"] },
    { type: "gdpr-compliance" as DocumentType, title: "GDPR Compliance Statement", description: "For Indian businesses with EU users. Data subject rights, DPIA, breach notification, and international transfers.", icon: <ShieldCheck className="w-6 h-6" />, color: "text-blue-700", bgColor: "bg-blue-50", borderColor: "border-blue-200", badge: "International", category: "Data", laws: ["GDPR (EU) 2016/679", "DPDP Act 2023", "IT Act 2000"] },
    { type: "data-processing-agreement" as DocumentType, title: "Data Processing Agreement", description: "Controller-processor roles, security measures, breach notification, audit rights, and data deletion.", icon: <Database className="w-6 h-6" />, color: "text-sky-700", bgColor: "bg-sky-50", borderColor: "border-sky-200", badge: "B2B", category: "Data", laws: ["DPDP Act 2023", "IT Act 2000", "CERT-In 2022"] },
    { type: "dmca-policy" as DocumentType, title: "DMCA & Copyright Policy", description: "Takedown notices, counter-notices, repeat infringer policy, safe harbour (Sec 79 IT Act), and fair dealing.", icon: <AlertOctagon className="w-6 h-6" />, color: "text-fuchsia-700", bgColor: "bg-fuchsia-50", borderColor: "border-fuchsia-200", badge: "Content", category: "IP", laws: ["Copyright Act 1957", "IT Act 2000 (Sec 79)", "IT Rules 2021"] },
    { type: "content-moderation-policy" as DocumentType, title: "Content Moderation Policy", description: "Content categories, moderation methods, enforcement actions, appeals, transparency, and grievance officer.", icon: <ShieldAlert className="w-6 h-6" />, color: "text-lime-700", bgColor: "bg-lime-50", borderColor: "border-lime-200", badge: "Platforms", category: "IP", laws: ["IT Act 2000 (Sec 67,69,79)", "IT Rules 2021", "BNS 2023"] },
];

export const BUSINESS_TYPES = [
    { id: "saas", label: "SaaS / Software", icon: <Smartphone className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "disclaimer", "acceptable-use-policy", "service-level-agreement", "end-user-license-agreement", "gdpr-compliance", "data-processing-agreement"] as DocumentType[] },
    { id: "ecommerce", label: "E-Commerce / D2C", icon: <ShoppingBag className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "refund-policy", "cookie-policy", "shipping-policy", "cancellation-policy", "return-policy", "disclaimer"] as DocumentType[] },
    { id: "hotel", label: "Hotel / Hospitality", icon: <Hotel className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "refund-policy", "cancellation-policy", "cookie-policy", "disclaimer"] as DocumentType[] },
    { id: "restaurant", label: "Restaurant / Food", icon: <UtensilsCrossed className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "refund-policy", "cancellation-policy", "cookie-policy", "disclaimer"] as DocumentType[] },
    { id: "healthcare", label: "Healthcare / Pharma", icon: <Stethoscope className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "disclaimer", "cookie-policy", "gdpr-compliance", "data-processing-agreement"] as DocumentType[] },
    { id: "education", label: "Education / EdTech", icon: <GraduationCap className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "disclaimer", "refund-policy", "cancellation-policy", "community-guidelines", "acceptable-use-policy"] as DocumentType[] },
    { id: "fintech", label: "Fintech / Finance", icon: <Landmark className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "disclaimer", "cookie-policy", "data-processing-agreement", "gdpr-compliance"] as DocumentType[] },
    { id: "realestate", label: "Real Estate", icon: <Building className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "disclaimer", "cancellation-policy", "refund-policy", "cookie-policy"] as DocumentType[] },
    { id: "content", label: "Content / Media", icon: <Film className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "disclaimer", "dmca-policy", "content-moderation-policy", "community-guidelines"] as DocumentType[] },
    { id: "marketplace", label: "Marketplace / Platform", icon: <Store className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "disclaimer", "refund-policy", "shipping-policy", "return-policy", "cancellation-policy", "acceptable-use-policy", "content-moderation-policy", "community-guidelines", "dmca-policy"] as DocumentType[] },
    { id: "agency", label: "Agency / Freelancer", icon: <Briefcase className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "disclaimer", "service-level-agreement"] as DocumentType[] },
    { id: "other", label: "Other Business", icon: <Building2 className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "disclaimer"] as DocumentType[] },
];

export const BUSINESS_CATEGORIES: Record<string, { icon: React.ReactNode; docs: string[]; desc: string; }> = {
    "SaaS & Software": { icon: <Code className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "acceptable-use-policy", "service-level-agreement", "disclaimer", "gdpr-compliance", "data-processing-agreement", "end-user-license-agreement"], desc: "Apps, platforms & software products" },
    "E-Commerce & D2C": { icon: <Truck className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "refund-policy", "shipping-policy", "cancellation-policy", "return-policy", "cookie-policy", "disclaimer"], desc: "Online stores & direct-to-consumer brands" },
    "Content & Social": { icon: <Users className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "community-guidelines", "dmca-policy", "content-moderation-policy", "acceptable-use-policy", "cookie-policy"], desc: "Social platforms, forums & UGC sites" },
    "Hotel & Hospitality": { icon: <Building2 className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "refund-policy", "cancellation-policy", "cookie-policy", "disclaimer"], desc: "Hotels, restaurants & travel businesses" },
    "Healthcare": { icon: <Heart className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "disclaimer", "cookie-policy", "refund-policy"], desc: "Clinics, telemedicine & health tech" },
    "Fintech & Finance": { icon: <TrendingUp className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "service-level-agreement", "disclaimer", "cookie-policy", "gdpr-compliance", "data-processing-agreement"], desc: "Payment apps, lending & financial services" },
    "Agency & Freelancer": { icon: <Lightbulb className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "disclaimer"], desc: "Design, dev & consulting agencies" },
    "Startup & General": { icon: <Zap className="w-5 h-5" />, docs: ["privacy-policy", "terms-of-service", "cookie-policy", "disclaimer", "refund-policy"], desc: "Any other business or startup" },
};