// src/lib/legalgen/eula.ts
import { LAW_REGISTRY, type FormData, type GeneratedDocument } from './types';
import { renderDocument, type RenderSection } from './shared/render';
import { escapeHtml, safeUrl, safeEmail } from './shared/security';

function today(): string {
  const d = new Date();
  return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });
}

export function generateEula(data: FormData): GeneratedDocument {
  // ─── 1. SAFELY EXTRACT ALL USER INPUTS ──────────────────────────────
  const businessName = escapeHtml((data.businessName as string) || '[Your Business Name]');
  const websiteUrl = safeUrl((data.websiteUrl as string) || '#');
  const email = safeEmail((data.email as string) || '[Your Email]');
  const softwareName = escapeHtml((data.softwareName as string) || `${businessName} Software`);
  const effectiveDate = escapeHtml((data.effectiveDate as string) || today());
  const version = escapeHtml((data.version as string) || '1.0');
  const governingState = escapeHtml((data.governingState as string) || 'Delhi');

  // ─── 2. BOOLEAN FLAGS ─────────────────────────────────────────────────
  const isSaaS = !!data.isSaaS; // Is it a cloud/web app?
  const hasMobileApp = !!data.hasMobileApp; // Is it an iOS/Android app?
  const isDownloadable = !!data.isDownloadable; // Is it downloadable desktop software?

  // ─── 3. BUILD RENDER SECTIONS ─────────────────────────────────────────
  const sections: RenderSection[] = [];

  // 1. Introduction & Acceptance
  sections.push({
    title: '1. Acknowledgment and Acceptance',
    content: `
      <p>This End User License Agreement ("EULA" or "Agreement") is a legally binding contract between you (either an individual or a single entity) and <strong>${businessName}</strong> ("we," "us," or "our") regarding your use of the <strong>${softwareName}</strong> software, including any associated media, printed materials, and online or electronic documentation (collectively, the "Software").</p>
      <p>By downloading, installing, accessing, or otherwise using the Software, you agree to be bound by the terms of this EULA. This electronic record is generated by a computer system and does not require any physical or digital signatures in accordance with the <strong>Information Technology Act, 2000</strong>.</p>
      <p>IF YOU DO NOT AGREE TO THE TERMS OF THIS EULA, DO NOT INSTALL, COPY, ACCESS, OR USE THE SOFTWARE.</p>`,
  });

  // 2. Grant of License
  sections.push({
    title: '2. Grant of License',
    content: `
      <p>Subject to your strict compliance with the terms of this Agreement, ${businessName} grants you a revocable, non-exclusive, non-transferable, limited license to download, install, and/or access the Software solely for your personal, non-commercial purposes (unless a commercial license has been explicitly purchased).</p>
      <p>This License does not grant you any ownership rights in the Software. All rights not expressly granted to you are reserved by ${businessName}.</p>`,
  });

  // 3. License Restrictions (Crucial for Software)
  sections.push({
    title: '3. License Restrictions',
    content: `
      <p>You agree not to, and you will not permit others to:</p>
      <ul>
        <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose, or otherwise commercially exploit the Software or make it available to any third party.</li>
        <li>Copy, modify, make derivative works of, disassemble, decrypt, reverse compile, or reverse engineer any part of the Software, in accordance with the protections afforded under the <strong>Copyright Act, 1957</strong>.</li>
        <li>Remove, alter, or obscure any proprietary notice (including any notice of copyright or trademark) of ${businessName} or its affiliates, partners, or suppliers.</li>
        <li>Use the Software for any purpose that is illegal or prohibited by this Agreement, or under any applicable Indian laws.</li>
      </ul>`,
  });

  // 4. Intellectual Property
  sections.push({
    title: '4. Intellectual Property Rights',
    content: `
      <p>The Software, including without limitation all copyrights, patents, trademarks, trade secrets, and other intellectual property rights, is the sole and exclusive property of ${businessName}.</p>
      <p>The Software is licensed, not sold. This EULA does not grant you any rights to trademarks or service marks belonging to ${businessName}. Any infringement of our intellectual property will be subject to strict legal action under Indian Intellectual Property laws.</p>`,
  });

  // 5. App Store / Mobile specific (conditional)
  if (hasMobileApp) {
    sections.push({
      title: '5. App Store Dependencies',
      content: `
        <p>If you accessed or downloaded the Software from an application store or distribution platform (such as the Apple App Store or Google Play Store), you acknowledge and agree that:</p>
        <ul>
          <li>This EULA is concluded between you and ${businessName}, and not with the App Store provider.</li>
          <li>The App Store provider has no obligation whatsoever to furnish any maintenance and support services with respect to the Software.</li>
          <li>In the event of any failure of the Software to conform to any applicable warranty, the App Store provider's liability is strictly limited to their own platform terms.</li>
        </ul>`,
    });
  }

  // 6. SaaS specific (conditional)
  if (isSaaS) {
    sections.push({
      title: '6. Hosted Services (SaaS) and Uptime',
      content: `
        <p>As the Software is provided as a Software-as-a-Service (SaaS) platform, ${businessName} will use commercially reasonable efforts to ensure the Software is available 24/7. However, access to the Software may be temporarily suspended for maintenance, upgrades, or emergency repairs, or due to telecommunications failures.</p>
        <p>We are not liable for any data loss, service interruption, or business disruption resulting from such downtime.</p>`,
    });
  }

  if (isDownloadable) {
    sections.push({
      title: '6a. Downloadable Software Terms',
      content: `
        <p>Where the Software is downloaded and installed on your device, this license permits installation on a limited number of devices as specified in your purchase or subscription terms. You are solely responsible for ensuring your device meets the minimum system requirements for the Software.</p>
        <p>You may not redistribute copies of the installation files to any third party. Upon termination of this Agreement, you must uninstall and permanently delete all copies of the Software from all devices on which it was installed.</p>`,
    });
  }

  // 7. Updates and Maintenance
  sections.push({
    title: '7. Updates and Upgrades',
    content: `
      <p>${businessName} may from time to time provide enhancements or improvements to the features/functionality of the Software, which may include patches, bug fixes, updates, upgrades, and other modifications ("Updates").</p>
      <p>Updates may modify or delete certain features and/or functionalities of the Software. You agree that ${businessName} has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the Software to you.</p>
      <p>You further agree that all Updates will be deemed to constitute an integral part of the Software and subject to the terms and conditions of this Agreement.</p>`,
  });

  // 8. Termination
  sections.push({
    title: '8. Term and Termination',
    content: `
      <p>This Agreement shall remain in effect until terminated by you or ${businessName}.</p>
      <p>${businessName} may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.</p>
      <p>This Agreement will terminate immediately, without prior notice from ${businessName}, in the event that you fail to comply with any provision of this Agreement. Upon termination, you shall cease all use of the Software and delete all copies of the Software from your mobile device, desktop, or server.</p>`,
  });

  // 9. Disclaimer of Warranties
  sections.push({
    title: '9. Disclaimer of Warranties',
    content: `
      <p>THE SOFTWARE IS PROVIDED TO YOU "AS IS" AND "AS AVAILABLE" AND WITH ALL FAULTS AND DEFECTS WITHOUT WARRANTY OF ANY KIND. TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, ${businessName} EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.</p>
      <p>Without limitation to the foregoing, ${businessName} provides no warranty or undertaking, and makes no representation of any kind that the Software will meet your requirements, achieve any intended results, be compatible or work with any other software, applications, systems or services, operate without interruption, meet any performance or reliability standards or be error-free.</p>`,
  });

  // 10. Limitation of Liability
  sections.push({
    title: '10. Limitation of Liability',
    content: `
      <p>Notwithstanding any damages that you might incur, the entire liability of ${businessName} and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the Software.</p>
      <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE INDIAN LAW, IN NO EVENT SHALL ${businessName} BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, FOR LOSS OF DATA OR OTHER INFORMATION, FOR BUSINESS INTERRUPTION, OR FOR PERSONAL INJURY) ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF OR INABILITY TO USE THE SOFTWARE.</p>`,
  });

  // 11. Governing Law
  sections.push({
    title: '11. Governing Law and Jurisdiction',
    content: `
      <p>This Agreement shall be governed by and construed in accordance with the laws of India, including the Indian Contract Act, 1872, the Copyright Act, 1957, and the Information Technology Act, 2000.</p>
      <p>Any disputes arising out of or in connection with this EULA shall be subject to the exclusive jurisdiction of the competent courts located in <strong>${governingState}, India</strong>.</p>`,
  });

  // 12. Contact Information
  sections.push({
    title: '12. Contact Information',
    content: `
      <p>If you have any questions about this Agreement, please contact us at:</p>
      <p>
        <strong>${businessName}</strong><br>
        <strong>Email:</strong> <a href="mailto:${email}">${email}</a>
      </p>`,
  });

  // ─── 4. FILTER ACTIVE SECTIONS ─────────────────────────────────────────
  const activeSections = sections.filter((s) => s.content.trim().length > 0);

  // ─── 5. RENDER DOCUMENT HTML ───────────────────────────────────────────
  const html = renderDocument({
    documentTitle: 'End User License Agreement (EULA)',
    businessName: businessName,
    effectiveDate: effectiveDate,
    version: version,
    sections: activeSections,
    preambleHtml: `<p><strong>Effective Date:</strong> ${effectiveDate} | <strong>Document Version:</strong> ${version}</p><p>Please read this End User License Agreement carefully before clicking the "I Agree" button, downloading, or using <strong>${softwareName}</strong>.</p>`,
  });

  // ─── 6. GENERATE PLAIN TEXT VERSION ──────────────────────────────────
  const text = html
    .replace(/<[^>]*>/g, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  // ─── 7. ATTACH LAW REGISTRY & RETURN ──────────────────────────────────
  const meityLaws = LAW_REGISTRY['MeitY'] || [];
  const lawJusticeLaws = LAW_REGISTRY['Law & Justice'] || [];

  const relevantLaws = [
    ...lawJusticeLaws.filter(l => l.name.includes('Contract')),
    ...meityLaws.filter(l => l.name.includes('Information Technology')),
    {
      name: "The Copyright Act, 1957",
      department: "Law & Justice", // <--- Added missing department property
      url: "https://copyright.gov.in/Documents/CopyrightRules1957.pdf"
    }
  ];

  return {
    html,
    text,
    title: `End User License Agreement - ${businessName}`,
    complianceInfo: {
      laws: relevantLaws,
      lastUpdated: new Date().toISOString(),
      jurisdiction: 'IN',
    },
  };
}