import { AlertTriangle, Scale } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/ui/alert';

interface LegalDisclaimerProps {
  documentType?: string;
  locale?: 'en' | 'hi' | 'ta' | 'mr';
}

const DISCLAIMER_TEXTS = {
  en: {
    title: '⚠️ DRAFT FOR REVIEW — NOT LEGAL ADVICE',
    message: 'This document was generated by LegalGen AI. It is intended as a starting point and MUST be reviewed by a qualified legal professional before publication. Laws vary by jurisdiction and this may not cover all requirements for your specific situation.',
    consultLawyer: 'Consult a qualified lawyer before publishing this document.',
    lastUpdated: `Last Updated: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`,
  },
  hi: {
    title: '⚠️ समीक्षा के लिए मसौदा — विधिक सलाह नहीं',
    message: 'यह दस्तावेज़ LegalGen AI द्वारा उत्पन्न किया गया है। यह प्रकाशन से पहले एक योग्य विधिक पेशेवर द्वारा समीक्षा किया जाना चाहिए।',
    consultLawyer: 'इस दस्तावेज़ को प्रकाशित करने से पहले एक योग्य वकील से परामर्श करें।',
    lastUpdated: `अंतिम अपडेट: ${new Date().toLocaleDateString('hi-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`,
  },
  // Add Tamil and Marathi...
};

export function LegalDisclaimer({ locale = 'en' }: LegalDisclaimerProps) {
  const texts = DISCLAIMER_TEXTS[locale] || DISCLAIMER_TEXTS.en;
  
  return (
    <Alert className="border-yellow-500 bg-yellow-50 dark:bg-yellow-950/20">
      <AlertTriangle className="h-4 w-4 text-yellow-600" />
      <AlertDescription className="space-y-2">
        <p className="font-semibold text-yellow-800 dark:text-yellow-200">
          {texts.title}
        </p>
        <p className="text-sm text-yellow-700 dark:text-yellow-300">
          {texts.message}
        </p>
        <div className="flex items-center gap-2 mt-3 pt-3 border-t border-yellow-200 dark:border-yellow-800">
          <Scale className="h-4 w-4 text-yellow-600" />
          <span className="text-xs text-yellow-600 dark:text-yellow-400">
            {texts.consultLawyer}
          </span>
        </div>
        <p className="text-xs text-yellow-500 mt-2">
          {texts.lastUpdated}
        </p>
      </AlertDescription>
    </Alert>
  );
}